{
 "title": "Federated data",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "label": "Region", "query": { "query": "label_values(region)" } }
  ]
 },
 "panels": [
  { "title": "Federated data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Up exporters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{region=~\".+\"}==1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scrape rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "avg by (region) (rate(promhttp_metric_handler_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Up Prometheus",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{exported_job=\"\"}==1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "avg by(exported_instance)(100*(rate(node_cpu_seconds_total{mode!=\"user\"}[1m])))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Region: $region", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }, "repeat": "region" },
  {
   "title": "Up exporters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{region=~\"$region\"}==1)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}