{
 "title": "My kube dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Nombre de pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_pod_container_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nombre services",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_service_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Conteneurs UP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_ready>0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Utilisation CPU globale",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total[1m])*100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods par namespace",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info) by(namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU par pod",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 4 },
   "targets": [
    {
     "expr": "sum by(container_label_io_kubernetes_pod_name)(rate(container_cpu_user_seconds_total{container_label_io_kubernetes_pod_name=~\".+\"}[1m])*100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU par namespace",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 4 },
   "targets": [
    {
     "expr": "sum by(container_label_io_kubernetes_pod_namespace)(rate(container_cpu_user_seconds_total{container_label_io_kubernetes_pod_name=~\".+\"}[1m])*100)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}