{
 "title": "TP5",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Nombre de Nginx dans le namespace my-apps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum((kube_pod_status_ready{namespace=\"my-apps\", condition=\"true\", pod=~\"nginx.*\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "100*(1 - (node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "(sum by(instance, core)((100*(1 - irate(node_cpu_seconds_total{mode=\"idle\"}[1m])))))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}