{
 "title": "App 6",
 "description": "Monitoring app6 (TP6)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app6_uptime_seconds", "legendFormat": "__auto" }
   ]
  },
  { "title": "Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app6_users_count_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Online Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app6_users_count_online", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Users Delta",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app6_users_count_new", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Online percent",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*(app6_users_count_online / app6_users_count_total)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "HTTP Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Requests",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 13 },
   "targets": [
    { "expr": "rate(app6_requests_total[1m])", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Errors",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 13 },
   "targets": [
    { "expr": "rate(app6_errors_total[1m])", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Error rate",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 13 },
   "targets": [
    {
     "expr": "100*(rate(app6_errors_total[1m])/rate(app6_requests_total[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "targets": [
    { "expr": "app6_requests_latency_seconds", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Requests",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(app6_db_requests_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Sensor 1",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app6_sensors_sensor1_temp_degrees",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 21, "x": 3, "y": 33 },
   "targets": [
    {
     "expr": "{__name__=~\"app6_sensors_sensor.*_temp_degrees\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Sensor 2",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app6_sensors_sensor2_temp_degrees",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sensor 3",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app6_sensors_sensor3_temp_degrees",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}